grpc:
  server:
    port: 9000

spring:
  application:
    name: NETFLIX
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://containers-us-west-165.railway.app:7148/railway?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:3lCrj61sXzBRivRzM287}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
